# Generated by Django 4.1.7 on 2023-10-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optician',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optician',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optician',
            name='prof_image',
            field=models.ImageField(null=True, upload_to='optic_images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='eye_image',
            field=models.ImageField(upload_to='eye_images/'),
        ),
    ]
