# Generated by Django 4.1.7 on 2023-10-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_care', '0003_remove_optician_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optician',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='optician',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
