# Generated by Django 4.1.7 on 2023-10-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_care', '0004_remove_optician_address_remove_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='optician',
            name='location_description',
            field=models.TextField(null=True),
        ),
    ]
