# Generated by Django 4.1.7 on 2023-10-31 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eye_care', '0005_remove_patient_user_optician_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='optician',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opticians', to=settings.AUTH_USER_MODEL),
        ),
    ]
