# Generated by Django 4.1.7 on 2023-11-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_care', '0007_contact_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='eye_condition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
