# Generated by Django 4.1.7 on 2023-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_care', '0008_alter_patient_eye_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='eye_condition',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
