# Generated by Django 4.1.7 on 2023-11-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_care', '0009_alter_patient_eye_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('first_name',), 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='optician',
        ),
    ]
