# Generated by Django 4.1.7 on 2023-11-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_care', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='registration_date',
        ),
    ]
